#!/bin/sh
## Current working directory
#$ -cwd
## Resource type F: qty 2
#$ -l f_node=2
## Maximum run time
#$ -l h_rt=05:00:00
#$ -N train_no_stop
#$ -m abe
#$ -M phmw500@york.ac.uk
## Initialize module command (don't remove)
. /etc/profile.d/modules.sh
# Load CUDA environment
module load cuda
## Load Intel compiler environment
module load intel
##Load cudnn/7.0
module load cudnn/7.0
##Load python
module load python

## Global variable declaration (must be done every time)
export CUDA_HOME=/apps/t3/sles12sp2/cuda/9.0.176
export LD_LIBRARY_PATH=/apps/t3/sles12sp2/cuda/9.0.176/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/apps/t3/sles12sp2/cuda/9.0.176/extras/CUPTI/lib64:$LD_LIBRARY_PATH

## Pip installation of dependencies
# pip install --upgrade pip --user
# pip install /home/0/18R55047/OpenNMT-py/requirements.txt --user
# pip install numpy --user

## Actual program
python /home/0/18R55047/OpenNMT-py/train.py -gpuid 0 1 2 3 -data /home/0/18R55047/corpora/subs_custom/no_stop/raw/shizen -save_model /home/0/18R55047/corpora/subs_custom/no_stop/raw/shizen_model
